# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_taskr.ui'
#
# Created: Sun Apr 18 17:13:55 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Taskr(object):
    def setupUi(self, Taskr):
        Taskr.setObjectName("Taskr")
        Taskr.resize(687, 480)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Taskr.sizePolicy().hasHeightForWidth())
        Taskr.setSizePolicy(sizePolicy)
        Taskr.setAutoFillBackground(False)
        self.formLayoutWidget = QtGui.QWidget(Taskr)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 336, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.textName = QtGui.QLineEdit(self.formLayoutWidget)
        self.textName.setObjectName("textName")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.textName)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.textDesc = QtGui.QLineEdit(self.formLayoutWidget)
        self.textDesc.setObjectName("textDesc")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.textDesc)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dateEdit = QtGui.QDateEdit(self.formLayoutWidget)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout.addWidget(self.dateEdit)
        self.timeEdit = QtGui.QTimeEdit(self.formLayoutWidget)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout.addWidget(self.timeEdit)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.comboPrio = QtGui.QComboBox(self.formLayoutWidget)
        self.comboPrio.setObjectName("comboPrio")
        self.comboPrio.addItem("")
        self.comboPrio.addItem("")
        self.comboPrio.addItem("")
        self.comboPrio.addItem("")
        self.comboPrio.addItem("")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboPrio)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.textTags = QtGui.QLineEdit(self.formLayoutWidget)
        self.textTags.setObjectName("textTags")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.textTags)
        self.btnCreate = QtGui.QPushButton(Taskr)
        self.btnCreate.setGeometry(QtCore.QRect(199, 180, 141, 27))
        self.btnCreate.setObjectName("btnCreate")
        self.table = QtGui.QTableWidget(Taskr)
        self.table.setGeometry(QtCore.QRect(150, 250, 531, 221))
        self.table.setObjectName("table")
        self.table.setColumnCount(5)
        self.table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        self.listTags = QtGui.QListWidget(Taskr)
        self.listTags.setGeometry(QtCore.QRect(10, 340, 131, 131))
        self.listTags.setObjectName("listTags")
        self.label_6 = QtGui.QLabel(Taskr)
        self.label_6.setGeometry(QtCore.QRect(10, 223, 71, 18))
        self.label_6.setObjectName("label_6")
        self.line = QtGui.QFrame(Taskr)
        self.line.setGeometry(QtCore.QRect(10, 210, 671, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_7 = QtGui.QLabel(Taskr)
        self.label_7.setGeometry(QtCore.QRect(20, 321, 62, 18))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(Taskr)
        self.label_8.setGeometry(QtCore.QRect(10, 250, 62, 18))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(Taskr)
        self.label_9.setGeometry(QtCore.QRect(360, 230, 62, 18))
        self.label_9.setObjectName("label_9")
        self.verticalLayoutWidget = QtGui.QWidget(Taskr)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 254, 81, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn1 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn1.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.btn1.setObjectName("btn1")
        self.horizontalLayout_3.addWidget(self.btn1)
        self.btn2 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn2.setStyleSheet("background-color: rgb(226, 49, 5);")
        self.btn2.setObjectName("btn2")
        self.horizontalLayout_3.addWidget(self.btn2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn3 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn3.setStyleSheet("background-color: rgb(167, 145, 36);")
        self.btn3.setObjectName("btn3")
        self.horizontalLayout_4.addWidget(self.btn3)
        self.btn4 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn4.setStyleSheet("background-color: rgb(206, 216, 90);")
        self.btn4.setObjectName("btn4")
        self.horizontalLayout_4.addWidget(self.btn4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn5 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn5.setStyleSheet("background-color: rgb(107, 105, 170);")
        self.btn5.setObjectName("btn5")
        self.horizontalLayout_5.addWidget(self.btn5)
        self.btnAll = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btnAll.setObjectName("btnAll")
        self.horizontalLayout_5.addWidget(self.btnAll)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.lblIcon = QtGui.QLabel(Taskr)
        self.lblIcon.setGeometry(QtCore.QRect(380, 10, 281, 181))
        self.lblIcon.setObjectName("lblIcon")
        self.btnClean = QtGui.QPushButton(Taskr)
        self.btnClean.setGeometry(QtCore.QRect(50, 180, 141, 27))
        self.btnClean.setObjectName("btnClean")

        self.retranslateUi(Taskr)
        self.comboPrio.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Taskr)

    def retranslateUi(self, Taskr):
        Taskr.setWindowTitle(QtGui.QApplication.translate("Taskr", "Taskr", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Taskr", "name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Taskr", "desc:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Taskr", "date:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Taskr", "prio:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboPrio.setItemText(0, QtGui.QApplication.translate("Taskr", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboPrio.setItemText(1, QtGui.QApplication.translate("Taskr", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboPrio.setItemText(2, QtGui.QApplication.translate("Taskr", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboPrio.setItemText(3, QtGui.QApplication.translate("Taskr", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboPrio.setItemText(4, QtGui.QApplication.translate("Taskr", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Taskr", "tags:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCreate.setText(QtGui.QApplication.translate("Taskr", "Create!", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Taskr", "Finished", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Taskr", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Taskr", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Taskr", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Taskr", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Taskr", "Search by", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Taskr", "Tags:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Taskr", "Priority:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Taskr", "Results:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn1.setText(QtGui.QApplication.translate("Taskr", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.btn2.setText(QtGui.QApplication.translate("Taskr", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.btn3.setText(QtGui.QApplication.translate("Taskr", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.btn4.setText(QtGui.QApplication.translate("Taskr", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.btn5.setText(QtGui.QApplication.translate("Taskr", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAll.setText(QtGui.QApplication.translate("Taskr", "all", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClean.setText(QtGui.QApplication.translate("Taskr", "Clean", None, QtGui.QApplication.UnicodeUTF8))

